{
 "title": "Eureka Load Test",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Eureka Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Eureka Server Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"citi-82591\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"citi-82591\"}"
    }
   ]
  },
  {
   "title": "GC events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count[1m])",
     "legendFormat": "{{action}} because {{cause}}"
    },
    {}
   ]
  },
  {
   "title": "Average GC Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum[1m])/rate(jvm_gc_pause_seconds_count[1m])",
     "legendFormat": "{{action}} because {{cause}}"
    }
   ]
  },
  { "title": "Load Tester", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Eureka /eureka/apps Response Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(applications_size_sum[1m])/rate(applications_size_count[1m])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Eureka Requests By Path and Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(eureka_requests_total[1m])",
     "legendFormat": "{{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Total requests by endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "eureka_requests_total", "legendFormat": "{{uri}} {{status}}" }
   ]
  }
 ]
}